# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Kamil Figiela
tagline:          ''
description:      'Hacker,<br/> Software Engineer,<br/> Ph.D. candidate.'
url:              http://kfigiela.github.io

author:
  name:           'Kamil Figiela'
  url:            https://github.com/kfigiela

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/kfigiela/kfigiela.github.io

social:
  github:         https://github.com/kfigiela
  linkedin:       https://linkedin.com/in/kfigiela
  email:          kamil.figiela@gmail.com

ga:
  id:             UA-49684412-1
  domain:         kfigiela.github.io

excerpt_separator: "---"
