# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kamil Figiela
tagline:          ''
description:      'Ph.D. candidate at <a href="http://agh.edu.pl">AGH</a>, Hacker,<br/> Co-founder of <a href="http://dropsport.com">Dropsport</a>.'
url:              http://kfigiela.github.io

author:
  name:           'Kamil Figiela'
  url:            https://github.com/kfigiela

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/kfigiela/kfigiela.github.io
  
social:
  github:         https://github.com/kfigiela
  linkedin:       https://linkedin.com/in/kfigiela
  email:          kfigiela@agh.edu.pl
  
ga:
  id:             UA-49684412-1
  domain:         kfigiela.github.io